### ISSUE TITLE
Removal not working after being persisted

### ISSUE THREAD

**Issue by macabu** [woylie/ecto_nested_changeset#129]
**Describe the bug**
I've tried out the example and it seems that if you save either the "toy" or "pet", their removal no longer works.

**To Reproduce**

1. Start the example
2. Add an owner, two pets and two toys
3. Save it
4. Go back to edit, and try to delete either a toy or a pet
5. See that clicking the "X" does

**Expected behavior**
Being able to delete either toy or pet once it is persisted.

**Library and language versions:**
- main branch

**Additional context**
I've not been able to reproduce the issue on 5566acdea0921459f7cb7be5561361ab57fbbf62. 

My theory is that it relates to the new `to_form` in Phoenix 1.7
- Reference: https://github.com/phoenixframework/phoenix_html/issues/418

**Comment by woylie** [comment]
Thanks for the report! I forgot to normalize the value for the `deleted?` flag. Fixed on the main branch.

**Comment by woylie** [comment]
Sorry, I was too fast...

**Comment by woylie** [comment]
Alright, in addition to the normalization, I used the input component from Phoenix 1.7 to render the hidden input for the delete flag. However, the value of that flag is `true`, which would result in `value={true}`, which is not the same as `value="true"`. Should be fixed now.

**Comment by macabu** [comment]
Thank you for the quick fix and the library 😃
